-- ETVS migration 004: Kenya national geography, BLAKE3 contract, and input scope
BEGIN;

CREATE TABLE IF NOT EXISTS etvs_regions (
    region_id TEXT PRIMARY KEY,
    region_name TEXT NOT NULL UNIQUE,
    classification_type TEXT NOT NULL DEFAULT 'ETVS_OPERATIONAL',
    classification_note TEXT NOT NULL
);

INSERT INTO etvs_regions(region_id,region_name,classification_note) VALUES
('REG-01','Coastal Region','Project-level six-region classification; not a constitutional county hierarchy.'),
('REG-02','South Eastern Region','Project-level six-region classification; not a constitutional county hierarchy.'),
('REG-03','Mt Kenya Region','Project-level six-region classification; not a constitutional county hierarchy.'),
('REG-04','Northern Region','Project-level six-region classification; not a constitutional county hierarchy.'),
('REG-05','North Rift Valley Region','Project-level six-region classification; not a constitutional county hierarchy.'),
('REG-06','Western Region','Project-level six-region classification; not a constitutional county hierarchy.')
ON CONFLICT(region_id) DO UPDATE SET region_name=EXCLUDED.region_name,classification_note=EXCLUDED.classification_note;

ALTER TABLE counties ADD COLUMN IF NOT EXISTS region_id TEXT;
ALTER TABLE counties DROP CONSTRAINT IF EXISTS fk_county_region;
ALTER TABLE counties
    ADD CONSTRAINT fk_county_region FOREIGN KEY(region_id)
    REFERENCES etvs_regions(region_id) ON UPDATE CASCADE ON DELETE RESTRICT;

-- ETVS uses BLAKE3-256 for new provenance fingerprints, result fingerprints,
-- and the audit hash chain. BLAKE3's default digest is 256 bits (64 hex chars).
ALTER TABLE source_documents ADD COLUMN IF NOT EXISTS hash_algorithm TEXT NOT NULL DEFAULT 'BLAKE3-256';
ALTER TABLE source_submissions ADD COLUMN IF NOT EXISTS hash_algorithm TEXT NOT NULL DEFAULT 'BLAKE3-256';
ALTER TABLE result_submissions ADD COLUMN IF NOT EXISTS hash_algorithm TEXT NOT NULL DEFAULT 'BLAKE3-256';
ALTER TABLE audit_findings ADD COLUMN IF NOT EXISTS hash_algorithm TEXT NOT NULL DEFAULT 'BLAKE3-256';

ALTER TABLE source_documents DROP CONSTRAINT IF EXISTS source_documents_hash_algorithm_check;
ALTER TABLE source_documents ADD CONSTRAINT source_documents_hash_algorithm_check CHECK (hash_algorithm='BLAKE3-256');
ALTER TABLE source_submissions DROP CONSTRAINT IF EXISTS source_submissions_hash_algorithm_check;
ALTER TABLE source_submissions ADD CONSTRAINT source_submissions_hash_algorithm_check CHECK (hash_algorithm='BLAKE3-256');
ALTER TABLE result_submissions DROP CONSTRAINT IF EXISTS result_submissions_hash_algorithm_check;
ALTER TABLE result_submissions ADD CONSTRAINT result_submissions_hash_algorithm_check CHECK (hash_algorithm='BLAKE3-256');
ALTER TABLE audit_findings DROP CONSTRAINT IF EXISTS audit_findings_hash_algorithm_check;
ALTER TABLE audit_findings ADD CONSTRAINT audit_findings_hash_algorithm_check CHECK (hash_algorithm='BLAKE3-256');

-- The initial input surface is deliberately narrow. Geography, positions,
-- candidates, ballot specifications/security metadata and audit tables are
-- reference/derived data for this phase, not user-entered source data.
CREATE TABLE IF NOT EXISTS etvs_input_scope (
    input_area TEXT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    description TEXT NOT NULL
);

INSERT INTO etvs_input_scope(input_area,enabled,description) VALUES
('POLLING_STATION_DETAILS',TRUE,'Election-specific polling-station configuration and registered-voter baseline.'),
('TURNOUT_OBSERVATION',TRUE,'Observed voters cast/turnout at a polling station; variable input.'),
('RESULT_SUBMISSION',TRUE,'Candidate result values by polling station, contest and version.'),
('BALLOT_ACCOUNTING',TRUE,'Contest-level ballot accounting linked to the station turnout observation.'),
('GEOGRAPHY_REFERENCE',FALSE,'Counties, constituencies and wards are loaded as controlled reference data.'),
('CANDIDATE_REFERENCE',FALSE,'Candidates/positions are controlled reference data in this phase.'),
('BALLOT_SECURITY_REFERENCE',FALSE,'Ballot specifications, stock and security metadata are controlled reference data in this phase.'),
('AUDIT_RESULTS',FALSE,'Audit findings are generated by ETVS and are not direct user input.')
ON CONFLICT(input_area) DO UPDATE SET enabled=EXCLUDED.enabled,description=EXCLUDED.description;

-- Hard bounds for variable station turnout/votes cast.
ALTER TABLE turnout_observations
    DROP CONSTRAINT IF EXISTS turnout_observations_voters_turnout_non_negative;
ALTER TABLE turnout_observations
    ADD CONSTRAINT turnout_observations_voters_turnout_non_negative CHECK (voters_turnout >= 0);

-- A database-level cross-row check is implemented by the audit engine:
-- latest voters_turnout must be <= the station's registered_voters.
-- Keeping the observed value independent is intentional for auditability.

CREATE INDEX IF NOT EXISTS idx_counties_region ON counties(region_id);
CREATE INDEX IF NOT EXISTS idx_etvs_regions_name ON etvs_regions(region_name);

COMMIT;
